# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml


pool:
  vmImage: windows-latest

steps:
- task: PowerShell@2
  displayName: Downloading build dependencies
  inputs:
    targetType: 'inline'
    script: |
      # Write your PowerShell commands here.
      curl https://defaultstoragewesteur114.blob.core.windows.net/ksp/Dependencies.zip -o Dependencies.zip
- task: ExtractFiles@1
  displayName: Extracting dependencies
  inputs:
    archiveFilePatterns: '**\Dependencies.zip'
    destinationFolder: '$(Build.SourcesDirectory)\OfCourseIStillLoveYou'
    cleanDestinationFolder: false
    overwriteExistingFiles: false

- task: PowerShell@2
  displayName: Creating artifacts folder
  inputs:
    targetType: 'inline'
    script: |
     New-Item -ItemType "directory" -Path $(Build.ArtifactStagingDirectory)/win-x64
     New-Item -ItemType "directory" -Path $(Build.ArtifactStagingDirectory)/linux-x64
     New-Item -ItemType "directory" -Path $(Build.ArtifactStagingDirectory)/osx-x64
- task: NuGetToolInstaller@1
  inputs:
    versionSpec:
- task: NuGetCommand@2
  inputs:
    command: 'restore'
    restoreSolution: '**/*.sln'
    feedsToUse: 'select'
- task: VSBuild@1
  inputs:
    solution: '**\*.sln'
    msbuildArgs: '-p:PreBuildEvent=;PostBuildEvent= -p:Version=1.0.$(Build.BuildId)'
    platform: 'Any Cpu'
    configuration: 'Release'
    msbuildArchitecture: 'x64'

- task: CopyFiles@2
  displayName: Copy mod binaries to windows artifact directory
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)\OfCourseIStillLoveYou\Distribution\'
    Contents: '**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)\win-x64\modbinaries'

- task: CopyFiles@2
  displayName: Copy mod binaries to linux artifact directory
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)\OfCourseIStillLoveYou\Distribution\'
    Contents: '**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)\win-x64\modbinaries'

- task: CopyFiles@2
  displayName: Copy mod binaries to osx artifact directory
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)\OfCourseIStillLoveYou\Distribution\'
    Contents: '**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)\osx-x64\modbinaries'

- task: CopyFiles@2
  displayName: Copy grpc native depedency for Windows
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)\OfCourseIStillLoveYou\Dependencies\win'
    Contents: '**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)\win-x64\modbinaries\GameData\OfCourseIStillLoveYou\Plugins'

- task: CopyFiles@2
  displayName: Copy grpc native depedency for Linux
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)\OfCourseIStillLoveYou\Dependencies\linux'
    Contents: '**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)\linux-x64\modbinaries\GameData\OfCourseIStillLoveYou\Plugins'
- task: CopyFiles@2
  displayName: Copy grpc native depedency for osx
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)\OfCourseIStillLoveYou\Dependencies\osx'
    Contents: '**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)\osx-x64\modbinaries\GameData\OfCourseIStillLoveYou\Plugins'
    
- task: DotNetCoreCLI@2
  displayName: Publishing Desktop win-x64
  inputs:
    command: 'publish'
    publishWebProjects: false
    projects: '**/OfCourseIStillLoveYou.DesktopClient.csproj'
    arguments: '--no-restore --no-build --configuration Release --runtime win-x64 --output $(Build.ArtifactStagingDirectory)\win-x64\desktopclient'

- task: DotNetCoreCLI@2
  displayName: Publishing Server win-x64
  inputs:
    command: 'publish'
    publishWebProjects: false
    projects: '**/OfCourseIStillLoveYou.Server.csproj'
    arguments: '--no-restore --no-build --configuration Release --runtime win-x64 --output $(Build.ArtifactStagingDirectory)\win-x64\server'

- task: DotNetCoreCLI@2
  displayName: Publishing Desktop linux-x64
  inputs:
    command: 'publish'
    publishWebProjects: false
    projects: '**/OfCourseIStillLoveYou.DesktopClient.csproj'
    arguments: '--no-restore --no-build --configuration Release --runtime linux-x64 --output $(Build.ArtifactStagingDirectory)\linux-x64\desktopclient'

- task: DotNetCoreCLI@2
  displayName: Publishing Server linux-x64
  inputs:
    command: 'publish'
    publishWebProjects: false
    projects: '**/OfCourseIStillLoveYou.Server.csproj'
    arguments: '--no-restore --no-build --configuration Release --runtime linux-x64 --output $(Build.ArtifactStagingDirectory)\linux-x64\server'

- task: DotNetCoreCLI@2
  displayName: Publishing Desktop osx-x64
  inputs:
    command: 'publish'
    publishWebProjects: false
    projects: '**/OfCourseIStillLoveYou.DesktopClient.csproj'
    arguments: '--no-restore --no-build --configuration Release --runtime osx-x64 --output $(Build.ArtifactStagingDirectory)\osx-x64\desktopclient'

- task: DotNetCoreCLI@2
  displayName: Publishing Server osx-x64
  inputs:
    command: 'publish'
    publishWebProjects: false
    projects: '**/OfCourseIStillLoveYou.Server.csproj'
    arguments: '--no-restore --no-build --configuration Release --runtime osx-x64 --output $(Build.ArtifactStagingDirectory)\osx-x64\server'


- task: PublishBuildArtifacts@1
  displayName: Publishing Windows Artifacts
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/win-x64'
    ArtifactName: 'OfCourseIStillLoveYou_Windows_v1.0.$(Build.BuildId)'
    publishLocation: 'Container'

- task: PublishBuildArtifacts@1
  displayName: Publishing Linux Artifacts
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/linux-x64'
    ArtifactName: 'OfCourseIStillLoveYou_linux_v1.0.$(Build.BuildId)'
    publishLocation: 'Container'

- task: PublishBuildArtifacts@1
  displayName: Publishing osx Artifacts
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/osx-x64'
    ArtifactName: 'OfCourseIStillLoveYou_osx_v1.0.$(Build.BuildId)'
    publishLocation: 'Container'

    
    


    

    
