# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml


pool:
  vmImage: ubuntu-latest

steps:
- task: PowerShell@2
  displayName: Downloading build dependencies
  inputs:
    targetType: 'inline'
    script: |
      # Write your PowerShell commands here.
      curl https://defaultstoragewesteur114.blob.core.windows.net/ksp/Dependencies.zip -o Dependencies.zip
- task: ExtractFiles@1
  displayName: Extracting dependencies
  inputs:
    archiveFilePatterns: '**/Dependencies.zip'
    destinationFolder: '$(Build.SourcesDirectory)/OfCourseIStillLoveYou'
    cleanDestinationFolder: true
    overwriteExistingFiles: false

- task: DotNetCoreCLI@2
  displayName: Publishing win-x64
  inputs:
    command: 'publish'
    publishWebProjects: false
    projects: './OfCourseIStillLoveYou/OfCourseIStillLoveYou.csproj'
    arguments: '--configuration Release --runtime win-x64 --output $(Build.BinariesDirectory)/win-x64 -p:PreBuildEvent=;PostBuildEvent='
